### ISSUE TITLE
Question: Does/how will it work with Internet Gateway installed?!

### ISSUE THREAD

**Issue by Spacey-Rat** [TheRealKillaruna/nano_pk#10]
Hi!
I've already got the Hargassner Internet Gateway installed and got my Nano PK in the Hargassner App. The internet gateway interface got an local IP address. Now I tried:

A) Connect a second network cable to the network socket next to the Hargassner touchscreen to my switch.
Here this connection got a hardware link but doesn't get an IP address (DHCP of course active) AND my other internet gateway connection drops: I get a message from Hargassner that my device lost its internet connection. 

B) Tried to enter/use the LAN IP from the internet gateway - but doing so doesn't give me any new sensors within HA so I guess this doesn't work.

Anyone any ideas here?

Thx!

**Comment by TheRealKillaruna** [comment]
As I don't have the Internet Gateway, I can't say anything about this. I have seen another integration somewhere that used the Gateway instead of the Hargassner device, this might be something you could try out.

**Comment by iamthe1st** [comment]
Hi,
for me it works with the gateway like that:
First connect the Control directly to your lan (no gatway), set your router to give always the same ip to this device.
Note the IP-Adress, this is the one to use for your configuration.
Get your Home-Assistent setup running - 
When you get it running, install the gateay in the middle between your Control and your LAN (like in the manual).

**Comment by nopbop** [comment]
> Hi, for me it works with the gateway like that: First connect the Control directly to your lan (no gatway), set your router to give always the same ip to this device. Note the IP-Adress, this is the one to use for your configuration. Get your Home-Assistent setup running - When you get it running, install the gateay in the middle between your Control and your LAN (like in the manual).

This works for me. Thank you.

**Comment by Spacey-Rat** [comment]
Tried my luck again today - but nothing. To sum up:

`KD=Hargassner
KT=Nano.2(.3) 15 Plus
SW=V14.0HAR.o3
HW=V1.2.0`

I've got the internet gateway which is "normally" connected to my switch for having the Hargassner-App running. The gateway is somewhere inside of the whole Nano unit, at least the network cable comes out from the back. Then I've got the network port next to the touchscreen on the front (covered by that rubber thing, next to the SD-Card slot).

Now unplugged the "gateway" cable and tried to connect the port on the front to my switch: The whole Nano unit restarted! After that the network port on the switch shows some connection for about 30 seconds and then turns off. The unit get's no IP whatever I try (it is set to automatically in the nano touchscreen in the network config section - Once it'd get an IP dynamically I could set it to a fixed one in my DHCP.). Even my Unifi control software shows me no connection on that port. 

Then I re-connect the "gateway" cable and the app is working again and the nano unit gets it's usual IP for the gateway.

Any more suggestions what to do?! Sorry if I misunderstood smth.

**Comment by iamthe1st** [comment]
Hi,
in the attachment you can find my working "custom_components\nano_pk" Folder and the relevant part of my working configuration.yaml

Please delete your "custom_components\nano_pk" Folder and replace it with the one from the ZIP.
Then replace your "configuration.yaml" with the content of the "configuration_Working_04-01-2024.yaml" 
Also change the IP address in the line "host: 192.168.178.38" with the ip of the your Hargassner unit.
[nano_pk.zip](https://github.com/TheRealKillaruna/nano_pk/files/13829014/nano_pk.zip)

Then reboot Home Assistant - then you should get all the values/sensors.

**Comment by Kk5519** [comment]
Thank you very much, that helped me a lot!
I have used your files, but unfortunately my structure (Hargassner software) is slightly different. 
I have now first adapted the configuration.yaml (without touching your other files) by transferring my structure (after correcting special characters) from the memory card. There is already a lot of reasonable data, but I still have to reduce it.
Maybe an integration of the current software version into the project makes sense. That's why I'm attaching the .DAQ file of the memory card and the configuration.yaml file that I changed.

[configration kk.zip](https://github.com/TheRealKillaruna/nano_pk/files/13830545/configration.kk.zip)

**Comment by iamthe1st** [comment]
The easiest way is to get all the data and only view/use the ones you are interested in.

The data layout and names changes sometimes, so the easiest way is to get all data and just ignore the not interesting stuff.

**Comment by TheRealKillaruna** [comment]
Since more people are using the integration for more different devices with different firmware versions, it will be challenging to support all variants with an easy default solution. Indeed, what should always work is to use the message format from your own DAQ logfile with full parameter set (as you are successfully doing it now, it seems).
