### ISSUE TITLE
Firmware 14.0HAR.o2

### ISSUE THREAD

**Issue by iamthe1st** [TheRealKillaruna/nano_pk#12]
Hi, 
my setup was running fine for nearly a year until today, 13:00.
My Hargassner app says an update was installed at this time.
I tried to get the DAQ File, but they are only very small, and the "DAQPRJ" entry stops abruptly at "id=20" -- even XML "/DAQPRJ" is missing.

I exchanged the Files in "Custom components" with the latet Version from Github and tried the Messageformat 14N and 14N2 - 
I also delted the content of "__pycache__"

but no luck.

Any ideas?

[DAQ00393.zip](https://github.com/TheRealKillaruna/nano_pk/files/12149706/DAQ00393.zip)

**Comment by iamthe1st** [comment]
Hi, this morning a full DAQ File was created, here the content of the "DAQPRJ" Line.
I got it working again :-)

`"<DAQPRJ><ANALOG><CHANNEL id='0' name='ZK' dop='0'/><CHANNEL id='1' name='O2' unit='%'/><CHANNEL id='2' name='O2soll' unit='%'/><CHANNEL id='3' name='TK' unit='°C'/><CHANNEL id='4' name='TKsoll' unit='°C' dop='0'/><CHANNEL id='5' name='TRL' unit='°C'/><CHANNEL id='6' name='TRLsoll' unit='°C' dop='0'/><CHANNEL id='7' name='Spreizung' unit='°C'/><CHANNEL id='8' name='TRG' unit='°C'/><CHANNEL id='9' name='SZist' unit='%' dop='0'/><CHANNEL id='10' name='SZsoll' unit='%'/><CHANNEL id='11' name='TPo' unit='°C'/><CHANNEL id='12' name='TPm' unit='°C'/><CHANNEL id='13' name='TPu' unit='°C'/><CHANNEL id='14' name='Puff Fuellgrad' unit='%' dop='0'/><CHANNEL id='15' name='Puffer_soll oben' unit='°C' dop='0'/><CHANNEL id='16' name='Puffer_soll unten' unit='°C' dop='0'/><CHANNEL id='17' name='PuffZustand' dop='0'/><CHANNEL id='18' name='Max Anf Kessel' dop='0'/><CHANNEL id='19' name='TFW' unit='°C' dop='0'/><CHANNEL id='20' name='Leistung' unit='%' dop='0'/><CHANNEL id='21' name='ESsoll' unit='%'/><CHANNEL id='22' name='min.Leist.TRG' unit='%'/><CHANNEL id='23' name='max.Leist.TRG' unit='%'/><CHANNEL id='24' name='max.Leist.Fuell' unit='%'/><CHANNEL id='25' name='max.Leist.TPO' unit='%'/><CHANNEL id='26' name='ESRegler' unit='%' dop='0'/><CHANNEL id='27' name='Regler K'/><CHANNEL id='28' name='KeBrstScale' unit='%' dop='0'/><CHANNEL id='29' name='Programm' dop='0'/><CHANNEL id='30' name='Stoerungs Nr' dop='0'/><CHANNEL id='31' name='Max Anf ZenPuf' unit='°C' dop='0'/><CHANNEL id='32' name='I Es' unit='mA' dop='0'/><CHANNEL id='33' name='I Ra' unit='mA' dop='0'/><CHANNEL id='34' name='I Aa' unit='mA' dop='0'/><CHANNEL id='35' name='I Sr' unit='mA' dop='0'/><CHANNEL id='36' name='I Rein' unit='mA' dop='0'/><CHANNEL id='37' name='LZ ES seit Fuell.' unit='Min' dop='0'/><CHANNEL id='38' name='LZ ES seit Ent.' unit='Min' dop='0'/><CHANNEL id='39' name='Anzahl Entasch.' dop='0'/><CHANNEL id='40' name='Anzahl SR Beweg.' dop='0'/><CHANNEL id='41' name='Lagerstand' unit='kg' dop='0'/><CHANNEL id='42' name='Verbrauchszaehler' unit='kg' dop='0'/><CHANNEL id='43' name='Heiz P Lambda' unit='W' dop='2'/><CHANNEL id='44' name='Heiz U Lambda' unit='V' dop='2'/><CHANNEL id='45' name='Heiz I Lambda' unit='mA' dop='0'/><CHANNEL id='46' name='U_Lambda' unit='mV'/><CHANNEL id='47' name='U Netzteil' unit='mV' dop='0'/><CHANNEL id='48' name='T Spuelung' unit='°C'/><CHANNEL id='49' name='BRT' unit='°C'/><CHANNEL id='50' name='Tplat' unit='°C' dop='0'/><CHANNEL id='51' name='TVG' unit='°C'/><CHANNEL id='52' name='TVG2' unit='°C'/><CHANNEL id='53' name='AIN17' unit='V'/><CHANNEL id='54' name='Taus' unit='°C'/><CHANNEL id='55' name='TA Gem.' unit='°C'/><CHANNEL id='56' name='Ext.HK Soll' unit='°C' dop='0'/><CHANNEL id='57' name='TVL_A' unit='°C'/><CHANNEL id='58' name='TVLs_A' unit='°C' dop='0'/><CHANNEL id='59' name='TRA_A' unit='°C'/><CHANNEL id='60' name='TRs_A' unit='°C'/><CHANNEL id='61' name='HKZustand_A' dop='0'/><CHANNEL id='62' name='FRA Zustand' dop='0'/><CHANNEL id='63' name='TVL_1' unit='°C'/><CHANNEL id='64' name='TVLs_1' unit='°C' dop='0'/><CHANNEL id='65' name='TRA_1' unit='°C'/><CHANNEL id='66' name='TRs_1' unit='°C'/><CHANNEL id='67' name='HKZustand_1' dop='0'/><CHANNEL id='68' name='FR1 Zustand' dop='0'/><CHANNEL id='69' name='TVL_2' unit='°C'/><CHANNEL id='70' name='TVLs_2' unit='°C' dop='0'/><CHANNEL id='71' name='TRA_2' unit='°C'/><CHANNEL id='72' name='TRs_2' unit='°C'/><CHANNEL id='73' name='HKZustand_2' dop='0'/><CHANNEL id='74' name='FR2 Zustand' dop='0'/><CHANNEL id='75' name='TVL_B' unit='°C'/><CHANNEL id='76' name='TVLs_B' unit='°C' dop='0'/><CHANNEL id='77' name='TRA_B' unit='°C'/><CHANNEL id='78' name='TRs_B' unit='°C'/><CHANNEL id='79' name='HKZustand_B' dop='0'/><CHANNEL id='80' name='FRB Zustand' dop='0'/><CHANNEL id='81' name='TBA' unit='°C'/><CHANNEL id='82' name='TBs_A' unit='°C' dop='0'/><CHANNEL id='83' name='TB1' unit='°C'/><CHANNEL id='84' name='TBs_1' unit='°C' dop='0'/><CHANNEL id='85' name='BoiZustand_1' dop='0'/><CHANNEL id='86' name='TBB' unit='°C'/><CHANNEL id='87' name='TBs_B' unit='°C' dop='0'/><CHANNEL id='88' name='HKR Anf' unit='°C'/><CHANNEL id='89' name='Anf. HKR0' unit='°C' dop='0'/><CHANNEL id='90' name='Anf. HKR1' unit='°C' dop='0'/><CHANNEL id='91' name='Anf. HKR2' unit='°C' dop='0'/><CHANNEL id='92' name='Anf. HKR3' unit='°C' dop='0'/><CHANNEL id='93' name='Anf. HKR4' unit='°C' dop='0'/><CHANNEL id='94' name='Anf. HKR5' unit='°C' dop='0'/><CHANNEL id='95' name='Anf. HKR6' unit='°C' dop='0'/><CHANNEL id='96' name='Anf. HKR7' unit='°C' dop='0'/><CHANNEL id='97' name='Anf. HKR8' unit='°C' dop='0'/><CHANNEL id='98' name='Anf. HKR9' unit='°C' dop='0'/><CHANNEL id='99' name='Anf. HKR10' unit='°C' dop='0'/><CHANNEL id='100' name='Anf. HKR11' unit='°C' dop='0'/><CHANNEL id='101' name='Anf. HKR12' unit='°C' dop='0'/><CHANNEL id='102' name='Anf. HKR13' unit='°C' dop='0'/><CHANNEL id='103' name='Anf. HKR14' unit='°C' dop='0'/><CHANNEL id='104' name='Anf. HKR15' unit='°C' dop='0'/></ANALOG><DIGITAL><CHANNEL id='0' bit='0' name='Stoerung'/><CHANNEL id='0' bit='1' name='Stb'/><CHANNEL id='0' bit='2' name='Fuellstand'/><CHANNEL id='0' bit='3' name='RLP/PuffP'/><CHANNEL id='0' bit='4' name='RLm_auf'/><CHANNEL id='0' bit='5' name='RLm_zu'/><CHANNEL id='0' bit='10' name='WS freig.'/><CHANNEL id='0' bit='11' name='Akt. Code'/><CHANNEL id='0' bit='14' name='FW Freig.'/><CHANNEL id='0' bit='15' name='gFlP'/><CHANNEL id='0' bit='16' name='gFlM auf'/><CHANNEL id='0' bit='17' name='gFlM zu'/><CHANNEL id='0' bit='18' name='gFl2P'/><CHANNEL id='0' bit='19' name='gFl2M auf'/><CHANNEL id='0' bit='20' name='gFl2M zu'/><CHANNEL id='1' bit='0' name='L Heiz.'/><CHANNEL id='1' bit='1' name='Z Heiz.'/><CHANNEL id='1' bit='2' name='Z Geb.'/><CHANNEL id='1' bit='3' name='AA Run'/><CHANNEL id='1' bit='4' name='AA Dir'/><CHANNEL id='1' bit='5' name='ES Run'/><CHANNEL id='1' bit='6' name='ES Dir'/><CHANNEL id='1' bit='7' name='AS Saug'/><CHANNEL id='1' bit='8' name='AS RA Run'/><CHANNEL id='1' bit='9' name='AS RA Dir'/><CHANNEL id='1' bit='10' name='Rein En'/><CHANNEL id='1' bit='11' name='Rein Run'/><CHANNEL id='1' bit='12' name='Es Rein Endl'/><CHANNEL id='1' bit='13' name='sAS Anf Fuell'/><CHANNEL id='2' bit='0' name='HKPA'/><CHANNEL id='2' bit='1' name='MAA'/><CHANNEL id='2' bit='2' name='MAZ'/><CHANNEL id='2' bit='3' name='HKP1'/><CHANNEL id='2' bit='4' name='M1A'/><CHANNEL id='2' bit='5' name='M1Z'/><CHANNEL id='2' bit='6' name='HKP2'/><CHANNEL id='2' bit='7' name='M2A'/><CHANNEL id='2' bit='8' name='M2Z'/><CHANNEL id='2' bit='9' name='HKP3'/><CHANNEL id='2' bit='10' name='M3A'/><CHANNEL id='2' bit='11' name='M3Z'/><CHANNEL id='2' bit='12' name='HKP4'/><CHANNEL id='2' bit='13' name='M4A'/><CHANNEL id='2' bit='14' name='M4Z'/><CHANNEL id='2' bit='15' name='HKP5'/><CHANNEL id='2' bit='16' name='M5A'/><CHANNEL id='2' bit='17' name='M5Z'/><CHANNEL id='2' bit='18' name='HKP6'/><CHANNEL id='2' bit='19' name='M6A'/><CHANNEL id='2' bit='20' name='M6Z'/><CHANNEL id='2' bit='21' name='HKPB'/><CHANNEL id='2' bit='22' name='MBA'/><CHANNEL id='2' bit='23' name='MBZ'/><CHANNEL id='3' bit='0' name='BPA'/><CHANNEL id='3' bit='1' name='BP1'/><CHANNEL id='3' bit='2' name='BP2'/><CHANNEL id='3' bit='3' name='BP3'/><CHANNEL id='3' bit='4' name='BPB'/><CHANNEL id='3' bit='5' name='BZPA'/><CHANNEL id='3' bit='6' name='BZP1'/><CHANNEL id='3' bit='7' name='BZP2'/><CHANNEL id='3' bit='8' name='BZP3'/><CHANNEL id='3' bit='9' name='BZPB'/><CHANNEL id='4' bit='0' name='Aschebox'/><CHANNEL id='4' bit='1' name='Netztrafo'/><CHANNEL id='4' bit='2' name='Netzrelais'/><CHANNEL id='4' bit='4' name='Lagerraum'/><CHANNEL id='4' bit='6' name='FLP'/><CHANNEL id='4' bit='8' name='ATW'/><CHANNEL id='4' bit='9' name='Entasch gesp.'/><CHANNEL id='4' bit='13' name='HKV'/><CHANNEL id='4' bit='14' name='Spuelung Aktiv'/><CHANNEL id='6' bit='0' name='EHK Anf'/><CHANNEL id='6' bit='2' name='EHK Anf2'/><CHANNEL id='6' bit='3' name='EHK Anf3'/><CHANNEL id='6' bit='4' name='EHKP'/><CHANNEL id='6' bit='6' name='EHKP2'/><CHANNEL id='6' bit='7' name='EHKP3'/><CHANNEL id='6' bit='8' name='KASK1 MinLeist'/><CHANNEL id='6' bit='9' name='KASK2 MinLeist'/><CHANNEL id='6' bit='10' name='KASK3 MinLeist'/><CHANNEL id='6' bit='11' name='KASK4 MinLeist'/><CHANNEL id='6' bit='12' name='KASK1 MaxLeist'/><CHANNEL id='6' bit='13' name='KASK2 MaxLeist'/><CHANNEL id='6' bit='14' name='KASK3 MaxLeist'/><CHANNEL id='6' bit='15' name='KASK4 MaxLeist'/><CHANNEL id='6' bit='16' name='KASK1 Run'/><CHANNEL id='6' bit='17' name='KASK2 Run'/><CHANNEL id='6' bit='18' name='KASK3 Run'/><CHANNEL id='6' bit='19' name='KASK4 Run'/><CHANNEL id='6' bit='20' name='KASK1 OK'/><CHANNEL id='6' bit='21' name='KASK2 OK'/><CHANNEL id='6' bit='22' name='KASK3 OK'/><CHANNEL id='6' bit='23' name='KASK4 OK'/><CHANNEL id='6' bit='24' name='Kask KWK Out'/><CHANNEL id='6' bit='25' name='Kask FW Out'/><CHANNEL id='6' bit='26' name='KASK KWK OK'/><CHANNEL id='6' bit='27' name='KASK FW OK'/><CHANNEL id='7' bit='0' name='DReg P2'/><CHANNEL id='7' bit='1' name='DReg P3'/><CHANNEL id='7' bit='2' name='DReg Mi auf'/><CHANNEL id='7' bit='3' name='DReg Mi zu'/><CHANNEL id='7' bit='5' name='DReg2 P2'/><CHANNEL id='7' bit='6' name='DReg2 Mi auf'/><CHANNEL id='7' bit='7' name='DReg2 Mi zu'/><CHANNEL id='7' bit='9' name='DReg3 P2'/><CHANNEL id='7' bit='10' name='DReg3 P3'/><CHANNEL id='7' bit='11' name='DReg3 Mi auf'/><CHANNEL id='7' bit='12' name='DReg3 Mi zu'/></DIGITAL></DAQPRJ>"`

**Comment by TheRealKillaruna** [comment]
Great that you got it working again!
