### ISSUE TITLE
Firmware 14.0HAR.o2 - again

### ISSUE THREAD

**Issue by anderl78** [TheRealKillaruna/nano_pk#14]
Can't get HA Integration with Firmware 14.0HAR.o2 online.. 
All sensores are on 'unknown' state. I used the NANO_V1403 with my nanopk. 14N2 has not worked, of course cleanen  __pycache__. I have seen somebody got it to work,  but there is no more Information how....

Any advice?

**Comment by kreiseder** [comment]
I am running it with this firmware version without problems. Have you followed the steps in the manual?

`https://github.com/TheRealKillaruna/nano_pk#how-to-use-with-other-hargassner-models-or-different-firmware-versions`

**Comment by anderl78** [comment]
Thank you! Yes, I already tried this too - doesn't work.... can you please post the msgformat- details from your setup?

**Comment by anderl78** [comment]
Oh my god.... I just looked again on my sd-card - there are around 100 daq-files, and I choose the oldest . Just did it again with the newest daq-file and it worked. 

Thank you
