### ISSUE TITLE
"ModuleNotFoundError: No module named 'apscheduler'"   after Home Assistant update

### ISSUE THREAD

**Issue by iamthe1st** [TheRealKillaruna/nano_pk#22]
Hi,
after the latest Home Assistant update i got this error:
ModuleNotFoundError: No module named 'apscheduler'

To fix it i just had to adjust this one Line in the "manifest.json" file:

  "requirements": ["apscheduler"],

After a restart everything was running fine again.

Please add this in github, so that others can avoid this issue.

I love your addon! It is running very stable and reliably for me!

**Comment by CalamityJenn** [comment]
Hi Iamth1st,

Thanks a lot for the tip, I was wondering how to make the addon load again! :)

**Comment by joe68ly** [comment]
Thanks, worked fine. Great work.

**Comment by TheRealKillaruna** [comment]
Fix is now merged into main branch, thanks!
