### ISSUE TITLE
FR35 ambient temperature missing

### ISSUE THREAD

**Issue by CalamityJenn** [TheRealKillaruna/nano_pk#4]
Hi, I cannot find any sensor relative to ambient temperature (FR35/FR75 value available through telnet).

**Comment by zLucPlayZ** [comment]
Whats your firmwere version?

**Comment by CalamityJenn** [comment]
It's v14l and it might upgrade to v14m05 anytime soon

**Comment by zLucPlayZ** [comment]
how can you Upgrade it? Now im interested. Also, you mentioned that the Parameter is not present in the Data you get. have you checked ur daq File?

**Comment by TheRealKillaruna** [comment]
Do you have an ambient temperature sensor installed and do the values display correctly on the heating itself?

**Comment by CalamityJenn** [comment]
@zLucPlayZ : you need the firmware on a SD card to upgrade from main screen.
@TheRealKillaruna : yes I do have a FR35 ambient temp sensor and I do have the correct temperature on main screen an on web interface. I also can see it through telnet but I did not find any sensor nor parameter relatives.

**Comment by mducommun** [comment]
Hi @CalamityJenn, did you find a way to get the ambient tep from your FR35?

**Comment by mducommun** [comment]
I spend some time this morning to look after this sensor and finally find it :
![image](https://user-images.githubusercontent.com/94470797/175026315-652e6a97-468e-440d-8439-7e29011a1145.png)
hope it will help!
