### ISSUE TITLE
stops working after a while - HA 7.x, NANO_V14M

### ISSUE THREAD

**Issue by ron84088** [TheRealKillaruna/nano_pk#5]
first of all - nice work, thank you very much!
this integration of my hargassner heating really leverages my move to ha ;-)

i have a hargassner nano-pk 2-25 in my basement with fw v14m5.
ha is running smoothly on a rpi4/1gb - currently os 7.2, core 2021.12.10, supervisor 2021.12.2.

issue:
NANO_PK value updates have always been freezing after a while (minutes/hours), which was a bit annoying, since it took a core restart to solve this. behaviour did not alter through several ha updates.

findings:
- obviously comm timing issues with telnet
- hargassner.py, l95: msgFormat is strictly set to 'V14L'
- hargassner.py, l107 ( self._scheduler.add_job(lambda:self._update(),'interval',seconds=update_interval) ) threw errors

stay healthy, ron

-- i would not mind, if you'd continue working on this cool integration :-p

**Comment by filzer666** [comment]
Hey Tobias,

worked quite well for a few days but now I have the same issues like Ron. Integration won't update anymore. If I change the parameters: STANDARD to FULL in configuration.yaml everything works fine again.

Appreciated!
Markus

**Comment by zLucPlayZ** [comment]
Like ron mentioned, if an error occurs, the integration will stop working. I have my own fork of this repo where I fixed those Issues. Feel free to check it out. I could also open a pull request to this repo.

**Comment by filzer666** [comment]
Hey Luca,

thanks for the quick reply! I've added your repo and it works fine out of the box. Will let you know when it fails ;)

Best Markus

**Comment by michi3120** [comment]
Hey, 

Im using this integration with my ECO HK wich is a woodchip heating and it also worked quite well first, but then i had the same problems as mentioned above. 
Now after using the repository of Luca it works great again.

So thanks to you both!!

**Comment by TheRealKillaruna** [comment]
Hi all, I have completely reworked the network code and message parsing of the integration. It would be great if you could try the latest version and report back if that resolves the issues you had. Thanks!

**Comment by TheRealKillaruna** [comment]
Resolved with the latest updates.
